# Generated by Django 5.2.4 on 2025-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sad_score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
